apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-loader
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-loader
  template:
    metadata:
      labels:
        app: data-loader
    spec:
      containers:
      - name: data-loader
        image: chaim022/data_loader:11

        ports:
        - containerPort: 8000
        env:
        - name: DB_HOST
          value: mysql
        - name: DB_USER
          value: root
        - name: DB_PASSWORD
          value: root_password
        - name: DB_NAME
          value: my_db




---
apiVersion: v1
kind: Service
metadata:
  name: data-loader
spec:
  selector:
    app: data-loader
  ports:
  - port: 8000
    targetPort: 8000
